export {default as Home} from './Home/Home';
export {default as Card} from './Card/Card';
export {default as NotFound} from './NotFound/NotFound';
export {default as Order} from './Order/Order';
export {default as Product} from './Product/Product';
export {default as Products} from './Products/Products';
export {default as Login} from './Register-Login/Login';
export {default as Register} from './Register-Login/Register';
export {default as Contact} from './Contact/Contact';
