// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Infrastructure.DataLayer;

#nullable disable

namespace Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "dbo");
                });

            modelBuilder.Entity("Shop.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address", "dbo");

                    b.HasData(
                        new
                        {
                            AddressId = new Guid("8a58c5f6-e9cb-4066-951d-f74a4d5c88d1"),
                            City = "Kavadarci",
                            Country = "Macedonia",
                            PostalCode = "1430",
                            Street = "Gorgi Sugare Br.90",
                            UserId = "392e10a6-af25-47bc-a99b-eb73a2f81b65"
                        },
                        new
                        {
                            AddressId = new Guid("d3db2f0c-19ee-4fb3-9ac4-475e2be5e47c"),
                            City = "Skopje",
                            Country = "Macedonia",
                            PostalCode = "1000",
                            Street = "Franklin Ruzvelt 50a 2/27",
                            UserId = "392e10a6-af25-47bc-a99b-eb73a2f81b65"
                        });
                });

            modelBuilder.Entity("Shop.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "392e10a6-af25-47bc-a99b-eb73a2f81b65",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9fc5e16d-0af9-4337-b6c0-b3c48b59e374",
                            Country = "Macedonia",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62a246b0-47af-42e5-a244-c0a0892c5f99",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Shop.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItem", "dbo");
                });

            modelBuilder.Entity("Shop.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("(GetDate())");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(5);

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(4);

                    b.Property<int>("TotalCost")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", "dbo");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("4b55da49-e4fd-4744-8e99-34e290673dd9"),
                            AddressId = new Guid("d3db2f0c-19ee-4fb3-9ac4-475e2be5e47c"),
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            PaymentMethod = "test",
                            TotalCost = 160,
                            UserId = "392e10a6-af25-47bc-a99b-eb73a2f81b65"
                        });
                });

            modelBuilder.Entity("Shop.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<int>("PriceAtPurchase")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", "dbo");

                    b.HasData(
                        new
                        {
                            OrderItemId = new Guid("d2417907-704a-44a7-8d2e-61cfab5e0f2d"),
                            OrderId = new Guid("4b55da49-e4fd-4744-8e99-34e290673dd9"),
                            PriceAtPurchase = 200,
                            ProductId = new Guid("5e326ee6-e48e-4b82-9b0c-f6b6e13b3c94"),
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = new Guid("bd22ec0a-0a45-4138-85c5-79a2ca979d0e"),
                            OrderId = new Guid("4b55da49-e4fd-4744-8e99-34e290673dd9"),
                            PriceAtPurchase = 100,
                            ProductId = new Guid("914a7eaf-1f86-43fa-8ff2-fde40a2d5d91"),
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = new Guid("4d03df58-cfce-42d0-afa5-8ab781fd382a"),
                            OrderId = new Guid("4b55da49-e4fd-4744-8e99-34e290673dd9"),
                            PriceAtPurchase = 300,
                            ProductId = new Guid("6d729ff2-c3b3-420a-a9e7-5dbd345ec0ce"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Shop.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("(GetDate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(4);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Product", "dbo");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("5e326ee6-e48e-4b82-9b0c-f6b6e13b3c94"),
                            Description = "Save up to £200 a year¹ with our best-selling original. It’s got all you need to lower your bills and shrink your carbon footprint.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/pdp-thermostat-hero1-temporary-pill@2x.png",
                            Price = 119,
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            ProductName = "Hive Thermostat",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("914a7eaf-1f86-43fa-8ff2-fde40a2d5d91"),
                            Description = "Save up to £200 a year¹ with our best-selling original. It’s got all you need to lower your bills and shrink your carbon footprint.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/thermostat-mini-hero-feb-sale.png",
                            Price = 79,
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            ProductName = "Hive Thermostat Mini",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("6d729ff2-c3b3-420a-a9e7-5dbd345ec0ce"),
                            Description = "Supercharge your savings and shrink your carbon footprint with handy budgeting tools, 24/7 efficiency monitoring and personalised suggestions to help you use less energy every day.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/Oct23/pdp-heatingplus-hero-new@b.png",
                            Price = 19,
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            ProductName = "Hive Heating Plus",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("ea78d2e6-26ac-49c0-a7e4-550f595e6d23"),
                            Description = "Set the perfect temperature in every room with smart radiator valves. Then save energy and money by never heating an empty room again.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/Oct23/TRV.png",
                            Price = 59,
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            ProductName = "Hive Radiator Valves",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("f2ca12fe-7d65-4e94-9772-41bca2a8c214"),
                            Description = "With a Hive Thermostat Frame your thermostat blends perfectly into your home, with colours matched to the Dulux™ signature colour range.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/1ybin0sD7OOgPQghmdeOgD/d678a444cb007e0f0113748db3a2a199/img-pdp_hero_frame_lifestyle_2x.jpeg",
                            Price = 500,
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            ProductName = "Hive Thermostat Frame",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("c9725e3b-2306-4cf8-96d6-9efeaa924fd0"),
                            Description = "Specifically designed for both the Hive Thermostat and Hive Thermostat Mini, our premium stand keeps your smart thermostat secure – wherever you choose to put it.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/Oct23/Thermostat-Stand.png",
                            Price = 29,
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            ProductName = "Hive Thermostat Stand",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("7ddfe475-0e4b-4529-b21e-873c91bff958"),
                            Description = "Control these E27  B22 smart light bulbs from your Hive app or with your voice. Tap them on or off, adjust the brightness in a swipe and save energy using schedules. You can even use our smart sensors to turn them on automatically when you open the door or walk into the room.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/6WkACGS9wvpAOQh2tvzTlP/306bce1547e9d634105ddf62351fdb50/img-pdp_hero_e27_dimmable_2x.jpeg",
                            Price = 19,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "E27 B22 Smart Light Bulb",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("f5d0d37b-ae21-4c37-be28-a902b02bbedf"),
                            Description = "Control these GU10 spotlight bulbs from your Hive app or with your voice. Tap them on or off, adjust the brightness in a swipe and save energy using schedules. You can even use our smart sensors to turn them on automatically when you open the door or walk into the room.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/1KSdKT77RpgCnl0430G1v2/7fdfa2a2eeb808051e18b8ff05deef2e/img-pdp_hero_gu10_dimmable_2x.jpeg",
                            Price = 14,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "GU10 Smart Light Bulb",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("92e5fdaf-b601-4fdf-ac06-07cc51bf70c2"),
                            Description = "Control these E14 candlelight bulbs from your Hive app or with your voice. Tap them on or off, adjust the brightness in a swipe and save energy using schedules. You can even use our smart sensors to turn them on automatically when you open the door or walk into the room.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/2zRGkm83nRH3G4pBsbEDdB/4f2d7abbf3dfb34762ff4aa50ac05d57/img-pdp_hero_e14_dimmable_2x.jpeg",
                            Price = 19,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "E14 Smart Light Bulb",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("76516a11-3a35-46d3-8980-d8d7e38ead59"),
                            Description = "Our Hive Motion Sensors let you know everything’s okay back home so you can relax wherever you are. Check if there’s been motion at home and get notifications the moment anything happens. Connect it with other Hive devices for even smarter control of your home. Like turning on a hall light when someone walks past.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/4inBTGozGS4AXJyJkYNfqr/70cc4b0538bc2fa24dedae8e89ac20ac/img-pdp_hero_motion_sensor_2x.jpeg",
                            Price = 29,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive Motion Sensor",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("c8c51472-8d32-4a32-933d-efebed3fa29e"),
                            Description = "Save on wasted energy and create a fully automated home with Hive Motion Sensors. Connect them to your smart lights, plugs and more to get them working seamlessly around you.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/Oct23/Motion-Sensor.png",
                            Price = 29,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive Motion Sensors",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("75a266a8-1434-4dcd-872d-7707991f0749"),
                            Description = "Our Hive Window or Door Sensor is a smart sensor that lets you know everything’s okay at home. Check on our app to see if windows or doors are open or closed and get notifications if anything changes.Connect it with other Hive devices for even smarter control of your home. Like turning the heating off automatically if a window is opened.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/4q0tQOev1gbZbm865S1FkP/aa83fd4cb28f4228419556b62ec59245/img-pdp_hero_contact_sensor_2x.jpeg",
                            Price = 29,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive Window or Door Sensor",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("ab51a5a3-b28a-41a1-b4bd-ff18df66377c"),
                            Description = "Monitor power-hungry appliances and only ever use the energy you need with a Hive Plug. Simply connect it like a normal adaptor and transform any device in seconds.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/Oct23/Plug-Hero.png",
                            Price = 39,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive Plug",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("55a5f1c0-462b-4f7d-b673-647e1f546b37"),
                            Description = "Our essential Hive Hub is the brains of your smart home. It connects all your devices to the internet – and to each other. So you can control everything straight from your smartphone.",
                            ImageUrl = "https://www.britishgas.co.uk/aem6/content/dam/hive/product-landmark/images/Oct23/Hub-PDP-Hero.png",
                            Price = 60,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive Hub",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("4d15a842-fd7a-4769-a325-e873a855238c"),
                            Description = "Our Hive Signal Booster makes sure you can connect your Hive devices to your hub wherever they are. It's ideal if you've got a big house or Hive devices in your basement and loft.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/3Zkuloon5cGr9lC6dmRCcj/82a2f096552a3679d8866d2dcf8d279f/img-pdp_hero_signal_booster_dimensions_2x.jpeg",
                            Price = 29,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive Signal Booster",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("3c6b709a-cd4c-4fea-863c-6913f1fe5db1"),
                            Description = "One of the smallest home EV chargers around, yet powerful enough to fully charge the average EV battery from empty in under eight hours, the EO Mini Pro 3 is packed with in-built safety features. And with its sleek matte black finish, it certainly makes a style statement.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/u3QT41kxDTa6TnuDygqJC/550fedee527af538ed9045a6568a99fb/img-pdp_hero_ev_charger_eo_mini_pro_3_dimensions_2x.png",
                            Price = 1199,
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            ProductName = "Hive EV Charging with EO Mini Pro 3",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("42afae17-36e2-42fd-a9c9-ea5da1253286"),
                            Description = "With safety and reliability at the heart of its design, the Alfen Eve Single S-Line is housed in a weatherproof white casing. Able to fully charge an average battery from empty in under eight hours, it always has the latest features thanks to automatic over-the-air updates.",
                            ImageUrl = "https://images.ctfassets.net/mijf9lz5yt3u/1hZsDEEbIvqKNvL0547SBb/38e173aaec714f66b84ae517a7b42a77/img-pdp_hero_ev_charger_alfen_eve_single_sline_1_2x.jpeg",
                            Price = 29,
                            ProductCategoryId = new Guid("1745e8de-2eac-4ccb-b954-1d00435fe66c"),
                            ProductName = "Hive EV Charging with Alfen Eve S-Line",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("Shop.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("(GetDate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<string>("Desc")
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategory", "dbo");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = new Guid("7d6f45c8-a818-4336-8040-ea762e5c7990"),
                            Name = "Smart Heating"
                        },
                        new
                        {
                            ProductCategoryId = new Guid("02ddad74-fd36-4fd5-abef-112beebc92d5"),
                            Name = "Smart Home"
                        },
                        new
                        {
                            ProductCategoryId = new Guid("1745e8de-2eac-4ccb-b954-1d00435fe66c"),
                            Name = "EV Charging"
                        });
                });

            modelBuilder.Entity("Shop.Entities.ShoppingCart", b =>
                {
                    b.Property<Guid>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("(GetDate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCart", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shop.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shop.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shop.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Entities.Address", b =>
                {
                    b.HasOne("Shop.Entities.ApplicationUser", "User")
                        .WithMany("Address")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.Entities.CartItem", b =>
                {
                    b.HasOne("Shop.Entities.Product", "Product")
                        .WithMany("cartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Shop.Entities.Order", b =>
                {
                    b.HasOne("Shop.Entities.Address", "Addresses")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addresses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.Entities.OrderItem", b =>
                {
                    b.HasOne("Shop.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Entities.Product", b =>
                {
                    b.HasOne("Shop.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Shop.Entities.ShoppingCart", b =>
                {
                    b.HasOne("Shop.Entities.ApplicationUser", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shop.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Orders");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("Shop.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Shop.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("Shop.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Entities.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
